apiVersion: v1
kind: Namespace
metadata:
  name: kafka-advisor
  labels:
    app.kubernetes.io/part-of: kafka-advisor
    opendatahub.io/dashboard: "true"
    modelmesh-enabled: "false"
  annotations:
    openshift.io/display-name: "Kafka Advisor Agent"
