apiVersion: v1
kind: Secret
metadata:
  name: kafka-advisor-model-secret
  namespace: kafka-advisor
  labels:
    app.kubernetes.io/part-of: kafka-advisor
type: Opaque
stringData:
  MODEL_API_URL: "http://kafka-advisor-model-predictor.kafka-advisor.svc.cluster.local/v1"
  MODEL_API_KEY: ""
  MODEL_NAME: "mistral-7b-instruct"

