apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-advisor-sa
  namespace: kafka-advisor
  labels:
    app.kubernetes.io/part-of: kafka-advisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-advisor-crd-reader
  labels:
    app.kubernetes.io/part-of: kafka-advisor
rules:
  - apiGroups: ["kafka.strimzi.io"]
    resources:
      - kafkas
      - kafkatopics
      - kafkausers
      - kafkamirrormaker2s
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-advisor-crd-reader-binding
  labels:
    app.kubernetes.io/part-of: kafka-advisor
subjects:
  - kind: ServiceAccount
    name: kafka-advisor-sa
    namespace: kafka-advisor
roleRef:
  kind: ClusterRole
  name: kafka-advisor-crd-reader
  apiGroup: rbac.authorization.k8s.io

